"use client";
//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/NavBar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
  
{
  const [theme, setTheme] = useState<"dark" | ''>("")
  return (
    <html lang="en" className={theme}>
      <body className={inter.className}>
        <NavBar theme={theme} setTheme={setTheme}/>
        {children}
      </body>
    </html>
  );
}
